import bibleTools/books/base

func he*(self: BibleBook): string =
  ## Get the hebrew name of given book
  case self:
    of Genesis: "בְּרֵאשִׁית"
    of Exodus: "שְׁמֹות"
    of Leviticus: "וַיִּקְרָא"
    of Numbers: "בְּמִדְבַּר"
    of Deuteronomy: "דְּבָרִים"
    # of Jubilees: ""
    # of Enoch: ""
    # of Jasher: ""
    of Joshua: "יהושע"
    of Judges: "שופטים"
    of Samuel1: "שמואל א"
    of Samuel2: "שמואל ב"
    of Kings1: "מלכים א"
    of Kings2: "מלכים ב"
    of Isaiah: "ישעיהו"
    of Jeremiah: "ירמיהו"
    # of EpistleOfJeremiah: ""
    of Ezekiel: "יחזקאל"
    # of Tobit: ""
    # of Baruk1: ""
    # of Baruk2: ""
    of Hosea: "הושע"
    of Joel: "יואל"
    of Amos: "עמוס"
    of Obadiah: "עבדיהו"
    of Jonah: "יונה"
    of Micah: "מיכיה"
    of Nahum: "נחום"
    of Habakkuk: "חבקוק"
    of Zephaniah: "צפניה"
    of Haggai: "חגי"
    of Zechariah: "זכריהו"
    of Malachi: "מלאכי"
    of Psalms: "תהילים"
    of Proverbs: "משלי"
    of Job: "איוב"
    # of WisdomOfSolomon: ""
    # of Sirach: ""
    of SongOfSolomon: "שיר השירים"
    # of Ruth: ""
    of Lamentations: "איכה"
    of Ecclesiastes: "קהלת"
    of Esther: "אסתר"
    # of AdditionsToEsther: ""
    # of Judith: ""
    of Chronicles1: "דברי הימים א"
    of Chronicles2: "דברי הימים ב"
    # of PrayerOfManasseh: ""
    of Daniel: "דניאל"
    # of PrayerOfAzariah: ""
    # of Susanna: ""
    # of BelAndTheDragon: ""
    of Ezra: "עזרא"
    of Nehemiah: "נחמיהו"
    # of Ezra3: ""
    # of Ezra4: ""
    # of Maccabees1: ""
    # of Maccabees2: ""
    # of Maccabees3: ""
    # of Maccabees4: ""
    of Matthew: "מתתיהו"
    of Mark: "מרקוס"
    of Luke: "לוקא"
    of Acts: "מעשי השליחים"
    of James: "יעקב"
    of Peter1: "כיפא א"
    of Peter2: "כיפא ב"
    of Jude: "יהודה"
    of Timothy1: "טימותיאוס א"
    of Titus: "טיטוס"
    of Thessalonians1: "תסלוניקים א"
    of Thessalonians2: "תסלוניקיםב"
    of Romans: "רומים"
    of Galatians: "גלטים"
    of Timothy2: "טימותיאוס ב"
    of Corinthians1: "קורינתים א"
    of Corinthians2: "קורינתים ב"
    of Ephesians: "אפסים"
    of Philippians: "פיליפים"
    of Colossians: "קולוסים"
    of Philemon: "פילמון"
    of Hebrews: "עברים"
    of John: "יהוחנן"
    of John1: "יהוחנן א"
    of John2: "יהוחנן ב"
    of John3: "יהוחנן ג"
    of Revelation: "רז גלה"
    # else: "שם הספר לא ידוע"
    else: "Not added yet!"

func hebrewTransliteration*(self: BibleBook): string =
  ## Get the hebrew name of given book
  case self:
    of Genesis: "Bere'shiyth"
    of Exodus: "Shemoth"
    of Leviticus: "Vayiqra"
    of Numbers: "Bemidbar"
    of Deuteronomy: "Devariym"
    of Jubilees: "Yovheliym"
    of Enoch: "Chanok"
    of Jasher: "Yashar"
    of Joshua: "Yahusha"
    of Judges: "Shofetiym"
    of Samuel1: "Shemu'el Ri'shon"
    of Samuel2: "Shemu'el Sheniy"
    of Kings1: "Melekiym Ri'shon"
    of Kings2: "Melekiym Sheniy"
    of Isaiah: "Yesha'yahu"
    of Jeremiah: "Yirmeyahu"
    of EpistleOfJeremiah: "Cepher Yirmeyahu"
    of Ezekiel: "Yechezq'el"
    of Tobit: "Toviyahu"
    of Baruk1: "Baruk Ri'shon"
    of Baruk2: "Baruk Sheniy"
    of Hosea: "Husha"
    of Joel: "Yo'el"
    of Amos: "Amoc"
    of Obadiah: "Ovadyahu"
    of Jonah: "Yonah"
    of Micah: "Miykah"
    of Nahum: "Nachum"
    of Habakkuk: "Chabaqquq"
    of Zephaniah: "Tsephanyahu"
    of Haggai: "Chaggai"
    of Zechariah: "Zakaryahu"
    of Malachi: "Mal`Akiy"
    of Psalms: "Tehilliym"
    of Proverbs: "Mishlei"
    of Job: "Iyov"
    of WisdomOfSolomon: "Chokmah Shalomah"
    of Sirach: "Sirach"
    of SongOfSolomon: "Shiyr Hashiyriym"
    of Ruth: "Ruth"
    of Lamentations: "Qiynah"
    of Ecclesiastes: "Qoheleth"
    of Esther: "Ecter"
    of AdditionsToEsther: "Hadaccah"
    of Judith: "Yahudith"
    of Chronicles1: "Divrei Hayamiym Ri'shon"
    of Chronicles2: "Divrei Hayamiym Sheniy"
    of PrayerOfManasseh: "Tephillah Menashsheh"
    of Daniel: "Daniy'el"
    of PrayerOfAzariah: "Tephillah Azaryahu"
    of Susanna: "Shushanah"
    of BelAndTheDragon: "Ba`Al And The Dragon"
    of Ezra: "Ezra V'nechemyahu"
    of Nehemiah: "Ezra V'nechemyahu"
    of Ezra3: "Ezra Sheliyshiy"
    of Ezra4: "Ezra Reviy`Iy"
    of Maccabees1: "Makkabiym Ri'shon"
    of Maccabees2: "Makkabiym Sheniy"
    of Maccabees3: "Makkabiym Sheliyshiy"
    of Maccabees4: "Makkabiym Reviy`Iy"
    of Matthew: "Mattithyahu"
    of Mark: "Marqus"
    of Luke: "Luqas"
    of Acts: "Ma'asiym"
    of James: "Ya`Aqov"
    of Peter1: "Kepha Ri'shon"
    of Peter2: "Kepha Sheniy"
    of Jude: "Yahudah"
    of Timothy1: "Timotheus Ri'shon"
    of Titus: "Titus"
    of Thessalonians1: "Tasloniqiym Ri'shon"
    of Thessalonians2: "Tasloniqiym Sheniy"
    of Romans: "Romaiym"
    of Galatians: "Galatiym"
    of Timothy2: "Timotheus Sheniy"
    of Corinthians1: "Qorintiym Ri'shon"
    of Corinthians2: "Qorintiym Sheniy"
    of Ephesians: "Eph'siym"
    of Philippians: "Philippiym"
    of Colossians: "Qolasiym"
    of Philemon: "Philemon"
    of Hebrews: "Ivriym"
    of John: "Yochanon"
    of John1: "Yochanon Ri'shon"
    of John2: "Yochanon Sheniy"
    of John3: "Yochanon Sheliyshiy"
    of Revelation: "Chizayon"
    else: "Unknown book name"
